<?php
   $server = 'localhost';
   $user = 'root';
   $password = '';
   $database_name = 'shop_db';

   $conn= mysqli_connect($server,$user, $password, $database_name);

//    die function is used to terminate the script's execution and display an error message. In this case, 
// it displays the message.
//   "Connection failed: " followed by the detailed error message provided by mysqli_connect_error(). 
//   The mysqli_connect_error() function retrieves the last error message generated by the MySQL server.
   if (!$conn) {
        die("Connection failed: ".mysqli_connect_error());
}
?>